### ISSUE TITLE
ModelState returned has no key and errorMessages are JSON objects

### ISSUE THREAD

**Issue by minawalphonce** [richardlawley/WebApi-FluentValidation#3]
the response I got 
{"message":"The request is invalid.","modelState":{"":["{\"PropertyName\":\"Username\",\"ErrorMessage\":\"Username already exists\",\"AttemptedValue\":\"admin\",\"CustomState\":null}"]}}

the response that must be
{"message":"The request is invalid.","modelState":{"username":["Username already exists"]}}

**Comment by richardlawley** [comment]
This sounds like a problem with your validator, not my library.  I just call the normal validator in the same way it would normally be called, just instantiated differently.  If you're convinced it's a problem with this library, then please provide more information and code showing how to reproduce the problem.

**Comment by minawalphonce** [comment]
Well I kind of found the problem, I'm not using the ValidationActionFilter you wrote, I'm the ModelState way, 
I fixed my problem by modifying the library FluentValidationActionFilter.ShallowValidate 
line 102 the foreach to be like this 
foreach (var error in result.Errors)
                {
                    validationContext.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    isValid = false;
                }

this fixes my problem and make the modelState works fine.

**Comment by ChrisMondok** [comment]
We were seeing the same issue in our project, where errors were JSON-encoded by the time we went to read them from the model state. I made a pull request (#4) with the small change we used to get around this problem.

**Comment by richardlawley** [comment]
Version 1.0.0.0 released with these changes included.
