### ISSUE TITLE
Update to latest version of FluentValidation

### ISSUE THREAD

**Issue by Grepsy** [richardlawley/WebApi-FluentValidation#5]
After trying to integrate I found out this still references version 3.4.6.0 from FluentValidation. The latest version is 6.2.1. It would be great if this could be updated to use the latest version.

**Comment by richardlawley** [comment]
Does 6.2.1 actually break compatibility?  I use 5.6.2.0 and there are no problems.  The downside of me depending on the latest is that it only works on the latest version, whereas to my knowledge it works with all versions at the moment.

**Comment by Grepsy** [comment]
I'm getting an error when trying to implement the `IScopedValidatorFactory`.

`Error CS0012 The type 'IValidator<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'FluentValidation, Version=3.4.6.0, Culture=neutral, PublicKeyToken=a82054b837897c66'.`

Not sure if that's because of version 6 though. Do you have any binding redirects specified for FluentValidation?

I tried downgrading FluentValidation to 3.4.6.0 but that causes issues with other packages that depend on a later version.

**Comment by richardlawley** [comment]
Yes, there's a binding redirect (added automatically by nuget I believe).  If you don't have one, try adding the following:

  <dependentAssembly>
    <assemblyIdentity name="FluentValidation" publicKeyToken="a82054b837897c66" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-6.2.1.0" newVersion="6.2.1.0" />
  </dependentAssembly>

(Check the version, I edited it by hand from mine)

**Comment by Grepsy** [comment]
I've added the binding redirect but that doesn't resolve the issue. I'll try again next week with an empty project. Thanks for your support so far.

**Comment by richardlawley** [comment]
As a temporary workaround, try 5.6.2.0 if you're not using a 6 feature.
I'll look next week at upgrading to 6 myself and will update the project if
it is required.

**Comment by Grepsy** [comment]
I've tried downgrading to 5.6.2, changed the binding-redirects, but still get the same error. I've also created a new Web API project, installed both this package and fluentvalidation, but unfortunately can't make it work. There obviously must be some way to make it work, since you're using it, but I'm out of ideas what the difference may be.

**Comment by richardlawley** [comment]
I've updated my own projects to the latest version of FluentValidation now, and they work with no issues, which makes me think that you've got an issue with your binding redirects somehow.  What are the exact error messages you're receiving, and what do you have in the relevant app.config/web.config for fluent validation?

**Comment by Grepsy** [comment]
The error-message is exactly as mentioned above, and only occurs when I try and implement the `IScopedValidatorFactory`.

Would it help if I create a new simple as possible application to showcase the problem?

**Comment by richardlawley** [comment]
That would be sensible - I can't see any reason why this would be failing unless you had a reference problem.  Are you creating your own `ScopedValidatorFactory` or just using the one I provide?

**Comment by Grepsy** [comment]
Ahh, that seems to be the difference. I tried implementing `IScopedValidatorFactory` to work with my DI container. Didn't realize there was a default implementation. So binding to `ScopedValidatorFactory` does make everything compile.

Except now I run into exactly the same error on runtime, when setting up the binding. My binding code (using Ninject):

`kernel.Bind<IScopedValidatorFactory>().To<ScopedValidatorFactory>();`

**Comment by richardlawley** [comment]
I think you'll need to set up a demo project for me to see this - this all
works for me (though I use Autofac) using the same versions.  If you can
set up a minimal project which shows the problem, I'll take a look.

**Comment by phykas** [comment]
Same problem here, I was using unsigned FluentValidation assembly, I see that Richard is using a signed one, so I just changed to FluentValidation-Signed and it's working for me.

**Comment by richardlawley** [comment]
Ah, thanks for tracking down the cause of the issue!  When I first started out I signed my packages, and I've never really moved away from the signed FluentValidation packages.  I'll try and change at some point, as it doesn't really make sense for my unsigned project to depend on the signed FluentValidation!

**Comment by phykas** [comment]
No problem, keep up the good work... The library is working fine, dependencies are resolved, so thank you for that... :)
